# This file is part of the Lug package.
#
# (c) Eric GELOEN <geloen.eric@gmail.com>
#
# For the full copyright and license information, please read the LICENSE
# file that was distributed with this source code.

imports:
    - { resource: config.yml }
    - { resource: bundles/prod/framework.yml }
    - { resource: bundles/prod/monolog.yml }
